@startuml
Banner : + id: int
Banner : + gerar_html(): None

BlocoBanner : + id: int
BlocoBanner : + titulo: str
BlocoBanner : + texto: str
BlocoBanner : + redirecionamento: str
BlocoBanner : + banner: int
BlocoBanner : + __str__(): str

Juncao : + id: int
Juncao : + coordenada: int[]
Juncao : + vizinhos: int[]

Amigo : + id: int
Amigo : + nome: str
Amigo : + coordenadas(): int[]
Amigo : + __str__(): str

Local : + id: int
Local : + nome: str
Local : + juncao: Juncao
Local : + banner: Banner
Local : + __str__(): str

Construcao : + id: int
Construcao : + local: Local

Piso : + id: int
Piso : + planta: Blob
Piso : + construcao: Construcao
Piso : + banner: Banner

Construcao -- Piso : 1..*
Piso -- Banner : 1
Construcao -- Banner : 1
Local -- Banner : 1
Local -- Juncao : 1
Juncao -- Juncao : *..*
BlocoBanner -- Banner : 1..*
@enduml